### ISSUE TITLE
Create separate leaderboards and then have an aggregation function

### ISSUE THREAD

**Issue by Zamiell** [Krakenos/BoIR-trueskill#12]
step 1)
make a seeded leaderboard and an unseeded touranment.
diversity counts as unseeded
also mixed count as unseeded (for the purposes of simplification)

step 2)
use an aggregation function to compute a 3rd leaderboard based on the results of leaderboards 1 and 2.
an example aggregation function is included at the bottom of the https://github.com/sublee/trueskill/issues/20

**Comment by Krakenos** [comment]
0d9d85882c61ab7890470348cd5a1db09adb8cb2 added only seperate leaderboards because of the problems with an aggregation function
