### ISSUE TITLE
Rename "json_creator.py" to "tournament_json_creator.py"

### ISSUE THREAD

**Issue by Zamiell** [Krakenos/BoIR-trueskill#24]

**Comment by Zamiell** [comment]
Also change:
`# Challonge API key used by json_creator.py`
to
`# Challonge API key used by "tournament_json_creator.py"`

**Comment by Krakenos** [comment]
770621078942361a1b9ffb5b58b5d38b2f599227 5c6c3a5d6836c86fe21ebef227e67aedf8bc5740
