### ISSUE TITLE
Make the script count tourney participation

### ISSUE THREAD

**Issue by Krakenos** [Krakenos/BoIR-trueskill#33]
Hide people who only played in 1 tourney for the leaderboards. Maybe count individual match ups while I am still at it?

**Comment by Zamiell** [comment]
probably more useful to just show whos participated on # of tournaments rather than # of matchups

**Comment by Krakenos** [comment]
yes, but I need to go through each match up anyway. Might aswell get some statistics on that in addition.

**Comment by Krakenos** [comment]
3aee147d522181d874d82d6d4c115956a24d9970
