### ISSUE TITLE
Make "api_key" read from an environment variable

### ISSUE THREAD

**Issue by Zamiell** [Krakenos/BoIR-trueskill#5]
Similar to how it works here:
https://github.com/Zamiell/isaac-racing-client/blob/master/release.py
Lines 56+57.
Lines 229.

Use the GitHub Python gitignore template:
https://github.com/github/gitignore

Also commit a .env_template file, and then change readme with instructions to copy `.env_template` to `.env`.

**Comment by Krakenos** [comment]
674041b2bf494340c92adc5b8a8a6d34c6367328
